version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/buzzfeed/sso
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: get lint
          command: go get github.com/golang/lint/golint
      - run:
          name: install dependencies
          command: |
            cp Godeps /tmp/Godeps
            cp gpm /tmp/gpm
            cd /tmp && ./gpm install
      - run:
          name: copy source
          command: |
            mkdir bin
      - run:
          name: run lint and tests for both services
          command: |
            scripts/test
      - run:
          name: build sso-auth
          command: |
            make dist/sso-auth
      - run:
          name: build sso-proxy
          command: |
            make dist/sso-proxy
      - run:
            name: push sso-dev image
            command: |
              if [[ -n $DOCKER_USER ]]; then
                docker login -u $DOCKER_USER -p $DOCKER_PASS
                make imagepush
              fi
